export const ADD_COMPONENT_TO_PLACEHOLDER = 'ADD_COMPONENT_TO_PLACEHOLDER'
export const REMOVE_COMPONENT_FROM_PLACEHOLDER =
  'REMOVE_COMPONENT_FROM_PLACEHOLDER'

export const SET_FIRST_OPERAND = 'SET_FIRST_OPERAND'
export const SET_SECOND_OPERAND = 'SET_SECOND_OPERAND'
export const SET_OPERATION = 'SET_OPERATION'
export const PERFORM_CALCULATION = 'PERFORM_CALCULATION'

export const CONSTRUCTOR_MODE = 'CONSTRUCTOR_MODE'
export const RUNTIME_MODE = 'RUNTIME_MODE'

export const DRAG_COMPONENT = 'DRAG_COMPONENT'
export const DROP_ON_COMPONENT = 'DROP_ON_COMPONENT'
